# Generated by Django 3.0.7 on 2020-06-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippingAddress',
            new_name='ShippingAddress',
        ),
    ]
